version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pet-social-postgres
    environment:
      POSTGRES_DB: pet_social_network
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pet-social-network

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pet-social-postgres:5432/pet_social_network
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - pet-social-network

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pet-social-postgres:5432/pet_social_network
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - pet-social-network

  event-service:
    build:
      context: ./event
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pet-social-postgres:5432/pet_social_network
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - pet-social-network

  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
      - event-service
    networks:
      - pet-social-network

networks:
  pet-social-network:
    driver: bridge

volumes:
  postgres_data: