server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/users/**, /api/pets/**
        - id: event-service
          uri: http://event-service:8083
          predicates:
            - Path=/api/events/**
